import "../globals.css";

import NextAuthProvider from "@/context/NextAuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import BottomBar from "@/components/shared/BottomBar/BottomBar";
import LeftSideBar from "@/components/shared/LeftSideBar/LeftSideBar";
import RightSideBar from "@/components/shared/RightSideBar/RightSideBar";

import MainContent from "@/components/shared/content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twitter-Threads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black h-screen`}>
        <NextAuthProvider>
          {/* Here add modals and toaster */}

          {/* Here add modals and toaster */}

          {/* Here add modals and toaster */}

          {/* Here add modals and toaster */}

          {/* <div className="container h-full mx-auto xl:px-30 max-w-6xl">
            <main className="grid lg:grid-cols-4 md:grid-cols-8 grid-cols-1 h-full">
              <LeftSideBar />

              <section
                className="
                col-span-1
                md:col-span-5
                lg:col-span-2
                border-x[1px] 
                border 
                border-neutral-800"
              >
                {children}
              </section>

              <RightSideBar />

              <BottomBar />
            </main>
          </div> */}

          <MainContent>{children}</MainContent>
        </NextAuthProvider>
      </body>
    </html>
  );
}
